version: "3.9"

services:
  captive_portal:
    build: .
    container_name: captive_portal
    ports:
      - "5009:5009"
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5009
    networks:
      - portalnet

networks:
  portalnet:
    driver: bridge
